---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: polly
  labels:
    app.kubernetes.io/name: polly
spec:
  replicas: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: polly
  template:
    metadata:
      labels:
        app.kubernetes.io/name: polly
      annotations:
        seccomp.security.alpha.kubernetes.io/pod: "runtime/default"
    spec:
      automountServiceAccountToken: false
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: app
          image: tylottr/polly:main
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 3000
          env:
            - name: MESSAGE
              value: We In Kubes
          resources:
            requests:
              cpu: 100m
              memory: 50Mi
            limits:
              cpu: 100m
              memory: 200Mi
          readinessProbe:
            initialDelaySeconds: 30
            httpGet:
              path: /health
              scheme: HTTP
              port: http
          livenessProbe:
            initialDelaySeconds: 60
            httpGet:
              path: /health
              scheme: HTTP
              port: http
          securityContext:
            allowPrivilegeEscalation: false
            privileged: false
            runAsNonRoot: true
            runAsUser: 1000
            capabilities:
              drop:
                - NET_RAW
                - ALL
