---
apiVersion: v1
kind: Service
metadata:
  name: polly
  labels:
    app.kubernetes.io/name: polly
spec:
  selector:
    app.kubernetes.io/name: polly
  type: ClusterIP
  ports:
    - name: http
      port: 3000
      targetPort: http
